### ISSUE TITLE
Offer option to limit number of output reads

### ISSUE THREAD

**Issue by jfy133** [maxibor/adrsm#2]
Another factor that could be considered when generating _in silico_ aDNA data is _sequencing effort_.

Currently `adrsm` will generate sequencing reads that are equivalent to a 'true sample', i.e., has the original full genomes at the requested genomic depth.

However, sequencing experiments themselves have a fixed limit which is the capacity of the machine (or the amount of DNA actually input into the machine). 

I would like to request the option for `adrsm` to output a user-defined set number of reads. For example, only have 10 million pairs in the output files. To simulate sequencing, these reads should be sampled randomly from within the initially sheared reads (which should have sampling probability represented by varying genome coverage).

**Comment by maxibor** [comment]
Added with bafdaca254406295303da443333184fbdcc6d75a

**Comment by jfy133** [comment]
Going to test now - but noticed one thing already: might be worth adding some docs what that actually means in terms of distribution of reads. The default effort seems very low though - maybe 1million would be better?
